title: Simon Turner's Cybersecurity Project Portfolio
description: Posting my project work as it pertains to computer security
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="simonturnerud" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://ca.linkedin.com/in/simonturnerud?trk=profile-badge">{YOUR NAME}</a></div>
